inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - 'yubioath.gemspec'

Metrics/LineLength:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/SpaceAroundOperators:
  Enabled: false

Style/SpaceInsideHashLiteralBraces:
  Enabled: false

Style/TrailingComma:
  EnforcedStyleForMultiline: comma

Style/BracesAroundHashParameters:
  Enabled: false

Style/IndentHash:
  Enabled: false
